services:
  ftp:
    image: delfer/alpine-ftp-server:latest
    container_name: ftp-server
    ports:
      - "21:21"
      - 21000-21010:21000-21010
    environment:
      - ADDRESS=192.168.1.205
      - FILE_OPEN_MODE=0666
      - LOCAL_UMASK=022
    volumes:
      - ./data:/ftp
    restart: always
